import { build } from 'esbuild'
import AdmZip from 'adm-zip'
import fs from 'fs'
import path from 'path'

const outDir = './build'
const outFile = 'index.js'
const zipFile = 'lambda.zip'

// Bundle JS
await build({
  entryPoints: ['./src'],
  outfile: path.join(outDir, outFile),
  platform: 'node',
  bundle: true,
  minify: true,
  sourcemap: true,
})

// Save what files where generated by esbuild
const generatedFiles = fs.readdirSync(outDir)

// Zip build folder for AWS lambda
var zip = new AdmZip()
zip.addLocalFolder(outDir)
zip.writeZip(path.join(outDir, zipFile))

// Remove all files that are not the zip
generatedFiles.forEach((file) => fs.unlinkSync(path.join(outDir, file)))
